helio:
  crud:
    # JDBC驱动类名，根据数据库类型自行修改
    db-driver-class: com.mysql.cj.jdbc.Driver
    # 数据库类型
    db-type: mysql
    # 数据库连接主机
    db-host: 127.0.0.1
    # 数据库端口
    db-port: 3306
    # 数据库登录账号
    db-username: root
    # 数据库登录密码
    db-password: root
    # 数据库名
    db-name: helio_boot
  web:
    logging:
      # 是否启用 Web 访问日志切面；开发、测试环境可以开启，生产环境不开启
      enabled: true

spring:
  data:
    redis:
      # Redis连接主机
      host: 127.0.0.1
      # Redis连接端口
      port: 6379
      # Redis登录密码；如果没有设置密码，请注释掉下面这行，避免向 Redis-server 发送 AUTH 鉴权请求，引发程序启动失败
      password:
      # Redis数据库序号
      database: 1

knife4j:
  # 生产环境务必设为true
  production: false

mybatis-plus:
  configuration:
    # 生产环境下建议去除该配置项，不在控制台打印SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

dromara:
  x-file-storage:
    # 文档：https://x-file-storage.xuyanwu.cn/
    # 默认使用 local-plus-1 存储平台
    default-platform: local-plus-1
    # 缩略图后缀
    thumbnail-suffix: ".min.jpg"
    local-plus: # 本地存储升级版，不使用的情况下可以不写
      - platform: local-plus-1 # 存储平台标识
        enable-storage: true  #启用存储
        enable-access: false #启用访问（线上请使用 Nginx 配置，效率更高）
        domain: "" # 访问域名，例如：“http://127.0.0.1:8030/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
        base-path: / # 基础路径
        path-patterns: /** # 访问路径
        storage-path: （实际本地存储路径，如 D:/local-plus-1） # 实际本地存储路径
    minio: # MinIO，由于 MinIO SDK 支持 AWS S3，其它兼容 AWS S3 协议的存储平台也都可配置在这里
      - platform: minio-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: （MinIO AK）
        secret-key: （MinIO SK）
        end-point: http://127.0.0.1:9000
        bucket-name: helio
        domain: http://127.0.0.1:9000/helio/ # 访问域名，注意“/”结尾，例如：http://minio.abc.com/abc/
        base-path: / # 基础路径
